language: ruby
sudo: false
cache: bundler
rvm:
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
  
jobs:
  allow_failures:
  - rvm: ruby-head

notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - 'weston@westonganger.com'
